language: python
python: "2.7"

os:
  - linux


env:
  global:
    - LOG=`git log -n 1 | grep Merge`
    - OLD=`echo $LOG | cut -d ' ' -f2`
    - NEW=`echo $LOG | cut -d ' ' -f3`
    - DIFF=`git diff --name-only --diff-filter=b $OLD...$NEW`
    - DIFF=$(echo $DIFF | grep -o -e '\b[^ ]*.py\b')
#    - CMD_PYTEST="coverage run -m pytest -vvv tests/test_component/test_amgr.py;coverage run -m pytest -vvv tests/test_component/test_modules.py;coverage run -m pytest -vvv tests/test_component/test_pipeline.py;coverage run -m pytest -vvv tests/test_component/test_rmgr_2.py;coverage run -m pytest -vvv tests/test_component/test_rmgr.py;coverage run -m pytest -vvv tests/test_component/test_stage.py;coverage run -m pytest -vvv tests/test_component/test_task.py;coverage run -m pytest -vvv tests/test_component/test_tmgr_2.py;coverage run -m pytest -vvv tests/test_component/test_tproc_rp_2.py;coverage run -m pytest -vvv tests/test_component/test_tproc_rp.py;coverage run -m pytest -vvv tests/test_component/test_tmgr.py;coverage run -m pytest -vvv tests/test_component/test_wfp.py;coverage run -m pytest -vvv tests/test_component/test_states.py;coverage run -m pytest -vvv tests/test_integration/test_*;coverage run -m pytest -vvv tests/test_issues/test_*;coverage run -m pytest -vvv tests/test_utils/test_*"
    - CMD_FLAKE8="if [[ ! -z \"$DIFF"\]]; then flake8 --config=.flake8 $DIFF; fi"
    - CMD_PYLINT="if [[ ! -z \"$DIFF"\]]; then pylint $DIFF; fi"
    - COVERAGE=false
  matrix:
#    - MAIN_CMD=$CMD_PYTEST COVERAGE=true
    - MAIN_CMD=$CMD_FLAKE8
    - MAIN_CMD=$CMD_PYLINT  
  
  
# command to install dependencies
install:
  - pip install .
  - pip install coverage
  - pip install flake8
  - pip install pylint
  - pip install codecov

before_script:
  - LOC=/home/travis/virtualenv/python2.7  # Location where VE is created on travis


script:
  - echo $MAIN_CMD
  - eval $MAIN_CMD

after_success:
  - |
    if [[ $COVERAGE == 'true' ]]; then \
      coverage combine; \
      coverage xml; \
      coverage report; \
      curl -s https://codecov.io/bash | bash
    fi
